/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all events with their registration counts */
        get: operations["listEvents"];
        put?: never;
        /** Create an event */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Get a single event */
        get: operations["getEvent"];
        /** Replace an event */
        put: operations["updateEvent"];
        post?: never;
        /** Delete an event */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/register": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register for an event (increment count by 1) */
        post: operations["registerForEvent"];
        /** Cancel a registration */
        delete: operations["cancelRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Event: {
            /** @example 1 */
            readonly id: number;
            /** @example All-hands Meeting */
            name: string;
            /**
             * Format: date
             * @example 2026-06-15
             */
            date: string;
            /** @example 42 */
            readonly registrations: number;
            /**
             * Format: date-time
             * @example 2026-05-23T09:00:00Z
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @example 2026-05-23T09:00:00Z
             */
            readonly updated_at: string;
        };
        EventRequest: {
            /** @example Team Lunch */
            name: string;
            /**
             * Format: date
             * @example 2026-06-20
             */
            date: string;
        };
        EventResource: {
            data: components["schemas"]["Event"];
        };
        EventCollection: {
            data: components["schemas"]["Event"][];
        };
        Error: {
            /** @example No query results for model [Event] 1 */
            message: string;
        };
        ValidationError: {
            /** @example The name field is required. */
            message: string;
            /**
             * @example {
             *       "name": [
             *         "The name field is required."
             *       ],
             *       "date": [
             *         "The date field must be a valid date."
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        /** @example 1 */
        EventId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCollection"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResource"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResource"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResource"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    registerForEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered - returns the event with its updated count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResource"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    cancelRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled - returns the event with its updated count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResource"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
